version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram_bot_postgres
    restart: always
    environment:
      POSTGRES_DB: dbmorning
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
