version: '3.8'

services:
  db:
    image: postgres:15
    container_name: telegram_bot_postgres
    restart: always
    environment:
      POSTGRES_DB: telegram_bot_db
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  telegram_bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: